### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-SMJSONAPI#1]
Using the lastest release.
I got a memory leak.
`12:11:17: [SM] Warning: plugin custom/SMJSONAPI.smx is using more than 100000 handles!`

**Comment by maxime1907** [comment]
ripext sends a copy of the saved handle when you do `.Get()` so if we want to free the nested json objects, we need to delete them in the same function where the `new` keyword belongs...

**Comment by maxime1907** [comment]
players active/connect in subscribe

**Comment by maxime1907** [comment]
OnClientPostAdminCheck in Forwards
